apiVersion: v1
kind: Service
metadata:
  name: webflux
  labels:
    app.kubernetes.io/name: webflux
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: webflux
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webflux
  labels:
    app.kubernetes.io/name: webflux
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webflux
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webflux
        app.kubernetes.io/instance: sad-markhor
    spec:
      containers:
        - name: webflux
          image: registry.netkiller.cn:5000/netkiller/webflux
          #imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: "KUBERNETES_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: webflux
data:
  application.properties: |-
    homepage: http://www.netkiller.cn