# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: 'Download latest JDK 17'
      run: |
        wget --no-verbose \
            --directory-prefix $RUNNER_TEMP \
            https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: jdkfile
        jdkFile: ${{ runner.temp }}/jdk-17_linux-x64_bin.tar.gz
    - name: Build with Maven
      run: mvn -B package --file pom.xml
